### ISSUE TITLE
Ytt crashes in lovely-ytt

### ISSUE THREAD

**Issue by wdonne** [crumbhole/argocd-lovely-plugin#354]
Hello,

I'm using version 0.23.0 of `lovely-ytt`. The log of `argocd-repo-server` contains the following error:

```
time="2023-12-07T17:17:59Z" level=error msg="finished unary call with code Unknown" error="Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code │
│  = Unknown desc = error generating manifests: `argocd-lovely-plugin` failed exit status 1: 2023/12/07 16:56:31 exit status 2: panic: Lines are 1 based\n\ngoroutine 1 [running]:\ngithub.com/vmware-tanz │
│ u/carvel-ytt/pkg/filepos.NewPosition(...)\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/filepos/position.go:20\ngithub.com/vmware-tanzu/carvel-ytt/pkg/filepos.NewPositionInFile(...)\n\tgithub.com/vmware-t │
│ anzu/carvel-ytt/pkg/filepos/position.go:27\ngithub.com/vmware-tanzu/carvel-ytt/pkg/yamlmeta.(*Parser).newPosition(...)\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/yamlmeta/parser.go:279\ngithub.com/vmwa │
│ re-tanzu/carvel-ytt/pkg/yamlmeta.(*Parser).correctLineNumInErr(0x4000077570, {0x6b6cc0, 0x4000083530}, 0xffffffffffffffff)\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/yamlmeta/parser.go:268 +0x210\ngith │
│ ub.com/vmware-tanzu/carvel-ytt/pkg/yamlmeta.(*Parser).ParseBytes(0x4000077570, {0x400015c800, 0x1c4, 0x200}, {0x40000c624b, 0x2f})\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/yamlmeta/parser.go:61 +0x29 │
│ 0\ngithub.com/vmware-tanzu/carvel-ytt/pkg/yamlmeta.NewDocumentSetFromBytes({0x400015c800, 0x1c4, 0x200}, {0x40?, 0xe1?, {0x40000c624b?, 0x319318?}})\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/yamlmeta/ │
│ document_set.go:21 +0xb8\ngithub.com/vmware-tanzu/carvel-ytt/pkg/workspace.(*TemplateLoader).EvalPlainYAML(0x40000b6660, 0x40000de5a0)\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/workspace/template_load │
│ er.go:150 +0x1f8\ngithub.com/vmware-tanzu/carvel-ytt/pkg/workspace.(*LibraryExecution).filesByAnnotation(0x4000077738?, {0x544c59, 0x12}, 0x0?)\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/workspace/libr │
│ ary_execution.go:150 +0xfc\ngithub.com/vmware-tanzu/carvel-ytt/pkg/workspace.(*LibraryExecution).schemaFiles(...)\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/workspace/library_execution.go:137\ngithub.c │
│ om/vmware-tanzu/carvel-ytt/pkg/workspace.(*LibraryExecution).Schemas(0x4000077970, {0x0, 0x0, 0x0})\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/workspace/library_execution.go:60 +0x1e0\ngithub.com/vmwar │
│ e-tanzu/carvel-ytt/pkg/cmd/template.(*Options).RunWithFiles(0x40000e1400, {{0x400011c310?, 0x551dfc?, 0x8585c?}}, {0x6bb360?, 0x4000118fc0})\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/cmd/template/cmd. │
│ go:136 +0x18c\ngithub.com/vmware-tanzu/carvel-ytt/pkg/cmd/template.(*Options).Run(0x40000e1400)\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/cmd/template/cmd.go:100 +0x324\ngithub.com/vmware-tanzu/carvel │
│ -ytt/pkg/cmd.NewCmd.func1(0x0?, {0x40000de500?, 0x0?, 0x0?})\n\tgithub.com/vmware-tanzu/carvel-ytt/pkg/cmd/template.go:22 +0x20\ngithub.com/cppforlife/cobrautil.DisallowExtraArgs.WrapRunEForCmd.func2. │
│ 1(0x0?, {0x40000de500, 0x0, 0x5})\n\tgithub.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0x6c\ngithub.com/vmware-tanzu/carvel-ytt/pkg/cmd.NewYttCmd.WrapRunEForCmd.func2.1(0x │
│ 40000e4700?, {0x40000de500, 0x0, 0x5})\n\tgithub.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0x6c\ngithub.com/spf13/cobra.(*Command).execute(0x4000130000, {0x40000b6130, 0x │
│ 5, 0x5})\n\tgithub.com/spf13/cobra@v1.7.0/command.go:940 +0x658\ngithub.com/spf13/cobra.(*Command).ExecuteC(0x4000130000)\n\tgithub.com/spf13/cobra@v1.7.0/command.go:1068 +0x320\ngithub.com/spf13/cobr │
│ a.(*Command).Execute(0x4000077ec8?)\n\tgithub.com/spf13/cobra@v1.7.0/command.go:992 +0x1c\nmain.main()\n\tgithub.com/vmware-tanzu/carvel-ytt/cmd/ytt/ytt.go:21 +0xc0" grpc.code=Unknown grpc.method=Gene │
│ rateManifest grpc.service=repository.RepoServerService grpc.start_time="2023-12-07T17:17:59Z" grpc.time_ms=1.531 span.kind=server system=grpc                                                            │
```

Best regards,

Werner.

**Comment by wdonne** [comment]
Helm charts don't work with ytt as explained in https://github.com/crumbhole/argocd-lovely-plugin/blob/main/doc/ytt.md, even when you only modify the values file. So, you have the pass in the `values.yaml` file, but that is inconvenient when propagating the plugin through a tree of "app of apps" recursively.

**Comment by Joibel** [comment]
Can you fix the documentation? The lovely authors don't use ytt.
